# Generated by Django 5.1 on 2024-10-09 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('product_description', models.TextField()),
                ('category', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_quantity', models.PositiveIntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('metal_type', models.CharField(max_length=255)),
                ('stone_type', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Unisex', 'Unisex')], default='Unisex', max_length=6)),
                ('occasion', models.CharField(max_length=255)),
                ('images', models.ImageField(default='', upload_to='pic/')),
                ('delivery_options', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tbl_login',
            fields=[
                ('login_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('reset_token', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('last_logout', models.DateTimeField(blank=True, null=True)),
                ('login_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ManyToManyField(blank=True, to='jewelryapp.product')),
                ('login', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='jewelryapp.tbl_login')),
            ],
        ),
        migrations.CreateModel(
            name='Tbl_staff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=50)),
                ('contact_details', models.CharField(max_length=15)),
                ('status', models.BooleanField(default=True)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewelryapp.tbl_login')),
            ],
        ),
        migrations.CreateModel(
            name='Tbl_user',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('phone', models.CharField(max_length=15)),
                ('status', models.BooleanField(default=True)),
                ('login', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jewelryapp.tbl_login')),
            ],
        ),
    ]
