# Generated by Django 5.1 on 2024-08-20 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_login',
            fields=[
                ('login_id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tbl_user',
            fields=[
                ('user_id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('phone', models.CharField(max_length=15)),
                ('login', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jewelryapp.tbl_login')),
            ],
        ),
    ]
