# Generated by Django 5.1 on 2024-09-23 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelryapp', '0003_tbl_login_reset_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_staff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=50)),
                ('contact_details', models.CharField(max_length=15)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewelryapp.tbl_login')),
            ],
        ),
    ]
