# Generated by Django 5.1 on 2024-09-23 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelryapp', '0004_tbl_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('product_description', models.TextField()),
                ('category', models.CharField(choices=[('Ring', 'Ring'), ('Earring', 'Earring'), ('Bracelet', 'Bracelet')], max_length=50)),
                ('subcategory', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('stock_quantity', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('material', models.CharField(max_length=255)),
                ('metal_type', models.CharField(max_length=255)),
                ('gemstones', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Unisex', 'Unisex')], max_length=10)),
                ('occasion', models.CharField(max_length=255)),
                ('images', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('try_at_home', models.BooleanField(default=False)),
                ('delivery_options', models.TextField()),
                ('return_policy', models.TextField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
