# Generated by Django 5.1 on 2024-09-24 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelryapp', '0005_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tbl_login',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbl_login',
            name='last_logout',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbl_login',
            name='login_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tbl_login',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tbl_staff',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tbl_user',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
