# Generated by Django 5.1 on 2024-10-10 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelryapp', '0006_remove_product_category_remove_product_metal_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metaltype',
            fields=[
                ('metaltype_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Stonetype',
            fields=[
                ('stonetype_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
