# Generated by Django 5.1 on 2024-09-24 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jewelryapp', '0007_remove_product_discount_remove_product_gemstones_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='material',
            new_name='stone_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
    ]
