# Generated by Django 5.1 on 2024-10-12 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelryapp', '0007_metaltype_stonetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='delivery_options',
        ),
        migrations.AddField(
            model_name='product',
            name='bestselling',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jewelryapp.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='home_delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='metal_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jewelryapp.metaltype'),
        ),
        migrations.AddField(
            model_name='product',
            name='stone_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jewelryapp.stonetype'),
        ),
        migrations.AddField(
            model_name='product',
            name='store_pickup',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Unisex', 'Unisex'), ('Kids', 'Kids'), ('Baby', 'Baby')], default='Unisex', max_length=6),
        ),
    ]
