# Generated by Django 5.1 on 2024-10-12 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jewelryapp', '0008_remove_product_delivery_options_product_bestselling_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='metal_type',
            new_name='metaltype',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='stone_type',
            new_name='stonetype',
        ),
    ]
