# Generated by Django 5.1 on 2024-10-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelryapp', '0009_rename_metal_type_product_metaltype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryattribute',
            name='datatype',
            field=models.CharField(choices=[('string', 'String'), ('number', 'Number'), ('date', 'Date'), ('boolean', 'Boolean')], default='string', max_length=50),
        ),
    ]
