# Generated by Django 5.1 on 2024-10-13 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jewelryapp', '0011_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
    ]
