# Generated by Django 5.1 on 2024-10-17 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jewelryapp', '0013_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
