# Generated by Django 5.1 on 2024-10-18 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelryapp', '0015_wishlist_wishlistitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='login',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to='jewelryapp.tbl_login'),
        ),
    ]
