# Generated by Django 5.1 on 2024-10-24 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jewelryapp', '0018_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
