# Generated by Django 5.1 on 2024-10-26 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelryapp', '0020_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
