# Generated by Django 5.1 on 2024-10-27 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelryapp', '0022_billing_order_orderitem_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewelryapp.tbl_user'),
        ),
    ]
